### ISSUE TITLE
Incorrect conditional of user vs assistant when creating history.

### ISSUE THREAD

**Issue by yornaath** [MoonKraken/rusty_llama#3]
Followed your example and it worked great, but noticed that the assistant treated me like its assistant xD.

https://github.com/Me163/rusty_llama/blob/6bd996fe3fc9ae5954e2bd2e083260e6c77f25e0/src/api.rs#L29

**Comment by Jasonvdmeijden** [comment]
Saw this too, quite a funny mistake

**Comment by MoonKraken** [comment]
thanks for catching this! indeed a pretty funny bug - I actually never noticed the model treating me like an assistant in my testing - very strange
